# Generated by Django 3.2 on 2022-08-26 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_act.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_instructor', models.BooleanField(default=False)),
                ('last_connect', models.DateTimeField(default=datetime.datetime(2022, 8, 26, 18, 28, 10, 869548))),
                ('image_user', models.ImageField(blank=True, default='users/default_user.png', null=True, upload_to=users_act.models.upload_location_user)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proffesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_link', models.IntegerField(choices=[(1, 'Gmail'), (2, 'Facebook'), (3, 'Instagram'), (4, 'Whatsapp'), (5, 'Github')], default=1)),
                ('link', models.URLField()),
                ('proffesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_act.proffesor')),
            ],
        ),
    ]
