# Generated by Django 3.2 on 2022-08-26 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_act', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 18, 55, 40, 945629)),
        ),
    ]
