# Generated by Django 3.2 on 2022-08-30 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_act', '0004_alter_usuario_last_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_connect',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 14, 40, 34, 70679)),
        ),
    ]
