# Generated by Django 3.2 on 2022-08-30 14:45

import comunication.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_auto_20220830_1440'),
        ('users_act', '0006_alter_usuario_last_connect'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('comment_nums', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to=comunication.models.upload_foro_messages)),
                ('documents', models.FileField(blank=True, null=True, upload_to=comunication.models.upload_foro_messages)),
                ('link', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('likes', models.ManyToManyField(blank=True, related_name='usuarios', to='users_act.Usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CommentForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('images_comment', models.ImageField(blank=True, null=True, upload_to=comunication.models.upload_foro_messages)),
                ('documents_comment', models.FileField(blank=True, null=True, upload_to=comunication.models.upload_foro_messages)),
                ('link_comment', models.URLField(blank=True, null=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comunication.messageforo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
    ]
