# Generated by Django 3.2 on 2022-08-26 18:28

import courses.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_act', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('resumen', models.TextField(blank=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('document', models.FileField(blank=True, upload_to=courses.models.upload_location_file_week)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Todos los niveles', 'Todos los niveles'), ('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default=1, max_length=20)),
                ('category', models.CharField(choices=[('Tegnologia', 'Tegnologia'), ('Administracion', 'Administracion'), ('Negocios', 'Negocios'), ('Contabilidad', 'Contabilidad'), ('Comunicacion', 'Comunicacion'), ('Salud', 'Salud'), ('Educacion', 'Educacion')], default=1, max_length=20)),
                ('tipo_producto', models.CharField(choices=[('Curso', 'Curso'), ('Programa Especializado', 'Programa Especializado')], default=1, max_length=30)),
                ('video_hours', models.FloatField(default=0)),
                ('student_num', models.IntegerField(default=0)),
                ('calification', models.FloatField(blank=True, default=0, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('img_course', models.ImageField(blank=True, upload_to=courses.models.upload_location_course)),
                ('img_certificate', models.ImageField(blank=True, null=True, upload_to=courses.models.upload_location_course)),
                ('end_course', models.BooleanField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.proffesor')),
                ('usuario', models.ManyToManyField(blank=True, to='users_act.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models.file_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description_file', models.FileField(blank=True, null=True, upload_to=courses.models.upload_location_homework_file)),
            ],
        ),
        migrations.CreateModel(
            name='LinkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.TextField(blank=True)),
                ('course_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_data', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=courses.models.upload_location_evaluation_file)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.proffesor')),
            ],
        ),
        migrations.CreateModel(
            name='MessageForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('images', models.ImageField(blank=True, null=True, upload_to=courses.models.upload_foro_messages)),
                ('documents', models.FileField(blank=True, null=True, upload_to=courses.models.upload_foro_messages)),
                ('link', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('likes', models.ManyToManyField(blank=True, related_name='usuarios', to='users_act.Usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LinkCLass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url_document', models.URLField()),
                ('class_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_documents', to='courses.classweek')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('description_file', models.ManyToManyField(blank=True, to='courses.FileContent')),
                ('link_content', models.ManyToManyField(blank=True, to='courses.LinkPage')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.proffesor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_class', models.BooleanField(default=False)),
                ('class_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histoty_class', to='courses.classweek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=courses.models.upload_location_evaluation_file)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('end_date', models.DateTimeField(verbose_name='date end')),
                ('porcentaje', models.IntegerField(default=25)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.proffesor')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document', models.FileField(blank=True, upload_to=courses.models.upload_location_file_week)),
                ('class_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.classweek')),
            ],
        ),
        migrations.CreateModel(
            name='CommentForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('images_comment', models.ImageField(blank=True, null=True, upload_to=courses.models.upload_foro_messages)),
                ('documents_comment', models.FileField(blank=True, null=True, upload_to=courses.models.upload_foro_messages)),
                ('link_comment', models.URLField(blank=True, null=True)),
                ('foro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.messageforo')),
            ],
        ),
        migrations.AddField(
            model_name='classweek',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_data', to='courses.week'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=courses.models.upload_certificate)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('porcentaje', models.IntegerField(default=25)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_calification', to='courses.evaluation')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=courses.models.upload_location_assigment_file)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='date end')),
                ('completed', models.BooleanField(default=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario')),
            ],
        ),
    ]
