# Generated by Django 3.2 on 2022-08-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_act', '0003_alter_usuario_last_connect'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentforo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users_act.usuario'),
            preserve_default=False,
        ),
    ]
