# Generated by Django 3.2 on 2022-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_commentforo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageforo',
            name='comment_nums',
            field=models.IntegerField(default=0),
        ),
    ]
