# Generated by Django 3.2 on 2022-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_messageforo_comment_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageforo',
            name='course',
        ),
        migrations.RemoveField(
            model_name='messageforo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='messageforo',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentForo',
        ),
        migrations.DeleteModel(
            name='MessageForo',
        ),
    ]
